### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by dotnetcomgazio** [nickv-oc/announcementcenter#16]
A zip to put on the root

En and Fr

http://s000.tinyupload.com/index.php?file_id=59268875601235089015

**Comment by nickvergessen** [comment]
How did you extract the language strings?

**Comment by dotnetcomgazio** [comment]
with my eyes on all pages (.php or .js) with something like "$l->t"

**Comment by dotnetcomgazio** [comment]
1 traduction more (appinfo)
Fr:
    "Announcements" => "Annonces",
En:
    "Announcements" => "Announcements",

**Comment by nickvergessen** [comment]
You missed `"The subject is too long or empty": "The subject is too long or empty",` as well,
whats the french version?

**Comment by dotnetcomgazio** [comment]
In French : "Le sujet est trop long ou vide"
