### ISSUE TITLE
Repository / AppStore Questions

### ISSUE THREAD

**Issue by aspdye** [nickv-oc/announcementcenter#18]
Hi,

Why is this app not created into the "ownCloud"-organisation? I think you are one of the employees of the ownCloud Inc. so that would make sense :smile: or not?

I cant find this app in the 8.2 app-store (in my instance). Is it a bug, or has it any reason?

**Comment by nickvergessen** [comment]
Appstore is broken, this app is not in the org, because I created it on my own, to be able to keep things simple.

**Comment by nickvergessen** [comment]
As you can see there is a download for 8.2
https://apps.owncloud.com/content/show.php?content=173921

If that does not work, then it is something that needs fixing in ownCloud itself.
